language: node_js
node_js:
 - "10.15.1"
dist: trusty
sudo: false

branches:
 only:
 - master

cache:
 directories:
   - node_modules

install:
 - npm install -g yarn

script:
 - npm run-script test
  - npm run-script build
deploy:
 provider: pages
 skip_cleanup: true
 github_token: 10fad4663c36664487f598b52d584fa8728fdfd2
 local_dir: dist
 on:
   branch: master
